In [ ]:
import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv("norwegian_financials_raw.csv")

df

,year,operating_revenue_nok_m,operating_profit_ebit_nok_m,interest_expense_nok_m,total_equity_nok_m,total_noncurrent_liabilities_nok_m,noncurrent_borrowings_nok_m,noncurrent_lease_liabilities_nok_m,current_assets_nok_m,inventory_nok_m,...,current_borrowings_nok_m,current_lease_liabilities_nok_m,employee_equivalent,employee_measure,total_assets_nok_m,retained_earnings_nok_m,total_liabilities_nok_m,year_end_share_price_nok,shares_outstanding,reported_market_cap_nok_m
0,2020,9095.7,-23768.4,2690.7,-6623.9,2679.4,0.0,185.7,37686.9,64.1,...,8769.9,3165.4,NaN,NaN,49554.0,-26882.7,56177.9,NaN,NaN,NaN
1,2021,5067.8,-2786.0,682.3,3269.6,9487.7,3981.6,4434.8,9864.1,16.3,...,183.1,777.9,1809.0,man-labor years,18825.4,-25029.8,15555.8,NaN,NaN,NaN
2,2022,18869.3,1502.3,650.0,4203.4,10842.3,4050.0,4646.2,10044.9,81.3,...,198.5,1190.6,3172.0,man-labor years,22669.6,-24117.1,18466.2,NaN,NaN,NaN
3,2023,25539.3,2232.1,848.0,5772.6,15816.9,3623.3,8688.8,13043.8,259.6,...,121.9,1591.4,3931.0,man-labor years,30550.0,-22526.9,24777.4,NaN,NaN,NaN
4,2024,35316.8,1872.6,1135.0,7240.7,17233.9,2947.6,9301.1,15253.8,501.6,...,1805.1,2023.5,7268.0,man-labor years,37600.1,-21359.0,30359.3,11.00,9.638805e+08,10600.0
5,2025,37646.0,3732.0,1271.0,7668.0,20335.0,3782.0,11930.0,14513.0,566.0,...,2065.0,1774.0,7398.0,full-time equivalent,42031.0,-18892.0,34364.0,17.45,1.055239e+09,18400.0

## 2.1 Profitability Ratio

### Operating Profit Margin

In [2]:
df["operating_profit_margin"] = (
    df["operating_profit_ebit_nok_m"]
    / df["operating_revenue_nok_m"]
) * 100

profit_margin_table = df.loc[
    df["year"].between(2021, 2025),
    [
        "year",
        "operating_revenue_nok_m",
        "operating_profit_ebit_nok_m",
        "operating_profit_margin"
    ]
].copy()

profit_margin_table

,year,operating_revenue_nok_m,operating_profit_ebit_nok_m,operating_profit_margin
1,2021,5067.8,-2786.0,-54.974545
2,2022,18869.3,1502.3,7.961610
3,2023,25539.3,2232.1,8.739864
4,2024,35316.8,1872.6,5.302292
5,2025,37646.0,3732.0,9.913404

### Return on Capital Employed (ROCE)

In [3]:
##Calculating Capital Employed
df["capital_employed"] = (
    df["total_equity_nok_m"]
    + df["total_noncurrent_liabilities_nok_m"]
)

df[[
    "year",
    "total_equity_nok_m",
    "total_noncurrent_liabilities_nok_m",
    "capital_employed"
]]

## calculate the average capital employed for each year and the ROCE for each year

df["average_capital_employed"] = (
    df["capital_employed"]
    + df["capital_employed"].shift(1)
) / 2

## ROCE Calculation:
df["roce"] = (
    df["operating_profit_ebit_nok_m"]
    / df["average_capital_employed"]
) * 100

##Displaying the ROCE table for the years 2021-2025

roce_table = df.loc[
    df["year"].between(2021, 2025),
    [
        "year",
        "operating_profit_ebit_nok_m",
        "capital_employed",
        "average_capital_employed",
        "roce"
    ]
].copy()

roce_table

,year,operating_profit_ebit_nok_m,capital_employed,average_capital_employed,roce
1,2021,-2786.0,12757.3,4406.40,-63.226216
2,2022,1502.3,15045.7,13901.50,10.806747
3,2023,2232.1,21589.5,18317.60,12.185548
4,2024,1872.6,24474.6,23032.05,8.130410
5,2025,3732.0,28003.0,26238.80,14.223211

In [ ]:
## Profitability table (Operating Profit Margin and ROCE) for the years 2021-2025

profitability = df.loc[
    df["year"].between(2021, 2025),
    [
        "year",
        "operating_profit_margin",
        "roce"
    ]
].copy()

profitability = profitability.rename(columns={
    "operating_profit_margin": "Operating Profit Margin (%)",
    "roce": "ROCE (%)"
})

profitability.round(2)

   year  Operating Profit Margin (%)  ROCE (%)
1  2021                       -54.97    -63.23
2  2022                         7.96     10.81
3  2023                         8.74     12.19
4  2024                         5.30      8.13
5  2025                         9.91     14.22

## 2.2 Efficiency

### Sales Revenue to Capital Employed

In [5]:
df["sales_to_capital_employed"] = (
    df["operating_revenue_nok_m"]
    / df["average_capital_employed"]
)

sales_capital_table = df.loc[
    df["year"].between(2021, 2025),
    [
        "year",
        "operating_revenue_nok_m",
        "average_capital_employed",
        "sales_to_capital_employed"
    ]
].copy()

sales_capital_table

,year,operating_revenue_nok_m,average_capital_employed,sales_to_capital_employed
1,2021,5067.8,4406.40,1.150100
2,2022,18869.3,13901.50,1.357357
3,2023,25539.3,18317.60,1.394249
4,2024,35316.8,23032.05,1.533376
5,2025,37646.0,26238.80,1.434745

### Sales Revenue per Employee

In [6]:
df["revenue_per_employee_nok_m"] = (
    df["operating_revenue_nok_m"]
    / df["employee_equivalent"]
)

employee_efficiency_table = df.loc[
    df["year"].between(2021, 2025),
    [
        "year",
        "operating_revenue_nok_m",
        "employee_equivalent",
        "employee_measure",
        "revenue_per_employee_nok_m"
    ]
].copy()

employee_efficiency_table

,year,operating_revenue_nok_m,employee_equivalent,employee_measure,revenue_per_employee_nok_m
1,2021,5067.8,1809.0,man-labor years,2.801437
2,2022,18869.3,3172.0,man-labor years,5.948707
3,2023,25539.3,3931.0,man-labor years,6.496896
4,2024,35316.8,7268.0,man-labor years,4.859218
5,2025,37646.0,7398.0,full-time equivalent,5.088673

In [7]:
##Final Efficiency table (Sales to Capital Employed and Revenue per Employee) for the years 2021-2025

efficiency = df.loc[
    df["year"].between(2021, 2025),
    [
        "year",
        "sales_to_capital_employed",
        "revenue_per_employee_nok_m"
    ]
].copy()

efficiency = efficiency.rename(columns={
    "sales_to_capital_employed": "Sales Revenue to Capital Employed (x)",
    "revenue_per_employee_nok_m": "Revenue per Employee (NOK m)"
})

efficiency.round(2)

   year  Sales Revenue to Capital Employed (x)  Revenue per Employee (NOK m)
1  2021                                   1.15                          2.80
2  2022                                   1.36                          5.95
3  2023                                   1.39                          6.50
4  2024                                   1.53                          4.86
5  2025                                   1.43                          5.09

### 2.3 Liquidity

## Current Ratio

In [8]:
df["current_ratio"] = (
    df["current_assets_nok_m"]
    / df["current_liabilities_nok_m"]
)

current_ratio_table = df.loc[
    df["year"].between(2021, 2025),
    [
        "year",
        "current_assets_nok_m",
        "current_liabilities_nok_m",
        "current_ratio"
    ]
].copy()

current_ratio_table

   year  current_assets_nok_m  current_liabilities_nok_m  current_ratio
1  2021                9864.1                     6068.0       1.625593
2  2022               10044.9                     7623.9       1.317554
3  2023               13043.8                     8960.5       1.455700
4  2024               15253.8                    13125.4       1.162159
5  2025               14513.0                    14028.0       1.034574

### Acid-Test Ratio

In [9]:
df["acid_test_ratio"] = (
    (df["current_assets_nok_m"] - df["inventory_nok_m"])
    / df["current_liabilities_nok_m"]
)

acid_test_table = df.loc[
    df["year"].between(2021, 2025),
    [
        "year",
        "current_assets_nok_m",
        "inventory_nok_m",
        "current_liabilities_nok_m",
        "acid_test_ratio"
    ]
].copy()

acid_test_table

,year,current_assets_nok_m,inventory_nok_m,current_liabilities_nok_m,acid_test_ratio
1,2021,9864.1,16.3,6068.0,1.622907
2,2022,10044.9,81.3,7623.9,1.306890
3,2023,13043.8,259.6,8960.5,1.426728
4,2024,15253.8,501.6,13125.4,1.123943
5,2025,14513.0,566.0,14028.0,0.994226

In [10]:
## Final Liquidity table (Current Ratio and Acid Test Ratio) for the years 2021-2025
liquidity = df.loc[
    df["year"].between(2021, 2025),
    [
        "year",
        "current_ratio",
        "acid_test_ratio"
    ]
].copy()

liquidity = liquidity.rename(columns={
    "current_ratio": "Current Ratio (x)",
    "acid_test_ratio": "Acid-Test Ratio (x)"
})

liquidity.round(2)

   year  Current Ratio (x)  Acid-Test Ratio (x)
1  2021               1.63                 1.62
2  2022               1.32                 1.31
3  2023               1.46                 1.43
4  2024               1.16                 1.12
5  2025               1.03                 0.99

### 2.4 Financial Gearing

### Gearing Ratio

In [11]:
df["noncurrent_interest_bearing_debt"] = (
    df["noncurrent_borrowings_nok_m"]
    + df["noncurrent_lease_liabilities_nok_m"]
)

df["gearing_ratio"] = (
    df["noncurrent_interest_bearing_debt"]
    / (
        df["total_equity_nok_m"]
        + df["noncurrent_interest_bearing_debt"]
    )
) * 100

### Final Gearing table (Gearing Ratio) for the years 2021-2025

gearing_table = df.loc[
    df["year"].between(2021, 2025),
    [
        "year",
        "total_equity_nok_m",
        "noncurrent_borrowings_nok_m",
        "noncurrent_lease_liabilities_nok_m",
        "noncurrent_interest_bearing_debt",
        "gearing_ratio"
    ]
].copy()

gearing_table

,year,total_equity_nok_m,noncurrent_borrowings_nok_m,noncurrent_lease_liabilities_nok_m,noncurrent_interest_bearing_debt,gearing_ratio
1,2021,3269.6,3981.6,4434.8,8416.4,72.021222
2,2022,4203.4,4050.0,4646.2,8696.2,67.414493
3,2023,5772.6,3623.3,8688.8,12312.1,68.080200
4,2024,7240.7,2947.6,9301.1,12248.7,62.848010
5,2025,7668.0,3782.0,11930.0,15712.0,67.202737

### Interest Cover Ratio

In [12]:
df["interest_cover"] = (
    df["operating_profit_ebit_nok_m"]
    / df["interest_expense_nok_m"]
)

interest_cover_table = df.loc[
    df["year"].between(2021, 2025),
    [
        "year",
        "operating_profit_ebit_nok_m",
        "interest_expense_nok_m",
        "interest_cover"
    ]
].copy()

interest_cover_table

   year  operating_profit_ebit_nok_m  interest_expense_nok_m  interest_cover
1  2021                      -2786.0                   682.3       -4.083248
2  2022                       1502.3                   650.0        2.311231
3  2023                       2232.1                   848.0        2.632193
4  2024                       1872.6                  1135.0        1.649868
5  2025                       3732.0                  1271.0        2.936271

In [13]:
## Financial gearing table (Gearing Ratio and Interest Cover) for the years 2021-2025
financial_gearing = df.loc[
    df["year"].between(2021, 2025),
    [
        "year",
        "gearing_ratio",
        "interest_cover"
    ]
].copy()

financial_gearing = financial_gearing.rename(columns={
    "gearing_ratio": "Gearing Ratio (%)",
    "interest_cover": "Interest Cover (x)"
})

financial_gearing.round(2)

   year  Gearing Ratio (%)  Interest Cover (x)
1  2021              72.02               -4.08
2  2022              67.41                2.31
3  2023              68.08                2.63
4  2024              62.85                1.65
5  2025              67.20                2.94